import type { Producer, ScanJob, OutreachEmail } from '@/types/database'

export const mockProducers: Producer[] = [
  {
    id: '1',
    created_at: '2024-01-15T10:00:00Z',
    writer_name: 'TreOnTheBeat',
    ipi_number: '00523847291',
    pro: 'ASCAP',
    publisher_status: 'NO_PUBLISHER',
    outreach_status: 'PENDING',
    ai_score: 87,
    priority: 'HIGH',
    estimated_monthly_royalties: 4200,
    instagram: '@treonthebeat',
    email: 'treonthebeat@gmail.com',
    twitter: null,
    spotify_streams: 8400000,
    catalog_count: 14,
    associated_artists: ['Lil Durk', 'EST Gee'],
    top_song: 'Back in Blood',
    reasoning: 'High-stream catalog with no publisher — significant uncollected performance royalties',
    notes: null,
  },
  {
    id: '2',
    created_at: '2024-01-16T10:00:00Z',
    writer_name: 'Chopsquad DJ',
    ipi_number: '00847362910',
    pro: 'BMI',
    publisher_status: 'SELF_PUBLISHED',
    outreach_status: 'PENDING',
    ai_score: 74,
    priority: 'HIGH',
    estimated_monthly_royalties: 2800,
    instagram: '@chopsquaddj',
    email: null,
    twitter: '@chopsquaddj',
    spotify_streams: 5200000,
    catalog_count: 22,
    associated_artists: ['Polo G', 'G Herbo'],
    top_song: 'Pop Out',
    reasoning: 'Self-published — missing sync and international mechanical royalties',
    notes: null,
  },
  {
    id: '3',
    created_at: '2024-01-17T10:00:00Z',
    writer_name: 'Roark Bailey',
    ipi_number: '00391847562',
    pro: 'ASCAP',
    publisher_status: 'NO_PUBLISHER',
    outreach_status: 'APPROVED',
    ai_score: 91,
    priority: 'HIGH',
    estimated_monthly_royalties: 6100,
    instagram: '@roarkbailey',
    email: 'roark@beatsbyme.com',
    twitter: null,
    spotify_streams: 12000000,
    catalog_count: 8,
    associated_artists: ['Rod Wave', 'Lil Baby'],
    top_song: 'Heart on Ice',
    reasoning: 'Mega-stream song with no publisher — highest priority lead in pipeline',
    notes: 'Very responsive on Instagram',
  },
  {
    id: '4',
    created_at: '2024-01-18T10:00:00Z',
    writer_name: 'D. Hill',
    ipi_number: '00748291037',
    pro: 'BMI',
    publisher_status: 'NO_PUBLISHER',
    outreach_status: 'SENT',
    ai_score: 68,
    priority: 'MEDIUM',
    estimated_monthly_royalties: 1900,
    instagram: '@dhill_music',
    email: 'dhill@protonmail.com',
    twitter: null,
    spotify_streams: 3100000,
    catalog_count: 6,
    associated_artists: ['42 Dugg'],
    top_song: 'Free Me',
    reasoning: 'Solid streams, multiple placements — good candidate for admin deal',
    notes: null,
  },
  {
    id: '5',
    created_at: '2024-01-19T10:00:00Z',
    writer_name: 'JetsonMade',
    ipi_number: '00293847561',
    pro: 'ASCAP',
    publisher_status: 'NO_PUBLISHER',
    outreach_status: 'OPENED',
    ai_score: 82,
    priority: 'HIGH',
    estimated_monthly_royalties: 3500,
    instagram: '@jetsonmade',
    email: null,
    twitter: '@jetsonmade',
    spotify_streams: 7800000,
    catalog_count: 31,
    associated_artists: ['Lil Baby', '21 Savage', 'Gunna'],
    top_song: 'Sold Out Dates',
    reasoning: 'Deep catalog with major artist placements — high lifetime royalty value',
    notes: 'Opened email twice — follow up',
  },
  {
    id: '6',
    created_at: '2024-01-20T10:00:00Z',
    writer_name: 'Bankroll Got It',
    ipi_number: '00561829374',
    pro: 'BMI',
    publisher_status: 'SELF_PUBLISHED',
    outreach_status: 'SKIPPED',
    ai_score: 45,
    priority: 'LOW',
    estimated_monthly_royalties: 800,
    instagram: '@bankrollgotit',
    email: null,
    twitter: null,
    spotify_streams: 1200000,
    catalog_count: 3,
    associated_artists: ['Moneybagg Yo'],
    top_song: 'Said Sum',
    reasoning: 'Low catalog depth limits upside — revisit if they get more placements',
    notes: 'Skipped — too few songs',
  },
  {
    id: '7',
    created_at: '2024-01-21T10:00:00Z',
    writer_name: 'Wheezy',
    ipi_number: '00192837465',
    pro: 'ASCAP',
    publisher_status: 'NO_PUBLISHER',
    outreach_status: 'REPLIED',
    ai_score: 95,
    priority: 'HIGH',
    estimated_monthly_royalties: 9200,
    instagram: '@wheezy',
    email: 'wheezy@gmail.com',
    twitter: '@wheezyouttahere',
    spotify_streams: 18500000,
    catalog_count: 47,
    associated_artists: ['Future', 'Young Thug', 'Gunna', 'Lil Baby'],
    top_song: 'Drip Too Hard',
    reasoning: 'Highest value lead — massive catalog, top-tier artists, zero publisher coverage',
    notes: 'REPLIED — interested! Schedule call ASAP',
  },
  {
    id: '8',
    created_at: '2024-01-22T10:00:00Z',
    writer_name: 'MexikoDro',
    ipi_number: '00384756192',
    pro: 'BMI',
    publisher_status: 'NO_PUBLISHER',
    outreach_status: 'PENDING',
    ai_score: 79,
    priority: 'HIGH',
    estimated_monthly_royalties: 3100,
    instagram: '@mexikodro',
    email: 'mexiko@beatsby.me',
    twitter: null,
    spotify_streams: 6400000,
    catalog_count: 19,
    associated_artists: ['Future', '21 Savage'],
    top_song: 'Jersey',
    reasoning: 'Consistent Future collaborator — valuable catalog with no publisher protection',
    notes: null,
  },
]

export const mockScanJobs: ScanJob[] = [
  {
    id: '1',
    created_at: '2024-01-22T08:00:00Z',
    started_at: '2024-01-22T08:00:05Z',
    completed_at: '2024-01-22T08:04:32Z',
    status: 'COMPLETED',
    artist_name: 'Lil Durk',
    songs_scanned: 20,
    writers_found: 34,
    leads_found: 8,
    error_message: null,
    triggered_by: 'manual',
  },
  {
    id: '2',
    created_at: '2024-01-22T09:00:00Z',
    started_at: '2024-01-22T09:00:05Z',
    completed_at: '2024-01-22T09:03:18Z',
    status: 'COMPLETED',
    artist_name: 'Polo G',
    songs_scanned: 20,
    writers_found: 28,
    leads_found: 5,
    error_message: null,
    triggered_by: 'manual',
  },
  {
    id: '3',
    created_at: '2024-01-22T10:00:00Z',
    started_at: '2024-01-22T10:00:05Z',
    completed_at: null,
    status: 'RUNNING',
    artist_name: 'Rod Wave',
    songs_scanned: 12,
    writers_found: 19,
    leads_found: 4,
    error_message: null,
    triggered_by: 'cron',
  },
  {
    id: '4',
    created_at: '2024-01-21T14:00:00Z',
    started_at: '2024-01-21T14:00:05Z',
    completed_at: '2024-01-21T14:06:44Z',
    status: 'COMPLETED',
    artist_name: 'NBA YoungBoy',
    songs_scanned: 20,
    writers_found: 41,
    leads_found: 12,
    error_message: null,
    triggered_by: 'cron',
  },
  {
    id: '5',
    created_at: '2024-01-21T15:30:00Z',
    started_at: '2024-01-21T15:30:05Z',
    completed_at: '2024-01-21T15:31:02Z',
    status: 'FAILED',
    artist_name: 'Future',
    songs_scanned: 3,
    writers_found: 0,
    leads_found: 0,
    error_message: 'Soundcharts rate limit exceeded',
    triggered_by: 'manual',
  },
]

export const mockEmails: OutreachEmail[] = [
  {
    id: '1',
    created_at: '2024-01-20T10:00:00Z',
    producer_id: '5',
    subject: 'Your beat on "Sold Out Dates" — $3,500/mo uncollected',
    body: `Hey JetsonMade,

Quick question — are you collecting your full publishing royalties on "Sold Out Dates"?

I run Reyes Music, a publishing admin company. We pulled your IPI and you have no publisher on record — which means every time that song plays on Spotify, Apple Music, YouTube, or gets licensed, you're only collecting writer's share. The publisher's share is just... gone.

On a song with 7.8M streams, we're talking roughly $3,500/month you're leaving on the table. Every month.

We do admin deals — no upfront cost, you keep your masters, you keep creative control. We handle all the backend: PRO registration, international collections, sync licensing, YouTube ContentID. Standard 15% admin fee, only on what we collect.

I'd love to hop on a 15-minute call and show you exactly what you're missing. No pitch, just data.

— David Reyes
Reyes Music × Raleigh MG
Miami, FL`,
    status: 'OPENED',
    sent_at: '2024-01-20T12:00:00Z',
    opened_at: '2024-01-21T09:15:00Z',
    clicked_at: null,
    replied_at: null,
    template_used: 'uncollected-royalties',
    sendgrid_message_id: 'msg_abc123',
  },
  {
    id: '2',
    created_at: '2024-01-19T10:00:00Z',
    producer_id: '7',
    subject: 'Your beat on "Drip Too Hard" — $9,200/mo uncollected',
    body: `Hey Wheezy,

"Drip Too Hard" is at 18.5M streams and climbing. Your IPI shows no publisher on record.

You're collecting writer's share. The publisher's share — an equal split — is uncollected. On a song this size, that's roughly $9,200 every month.

Reyes Music does publishing admin. No upfront cost. You keep everything. We just collect what's already yours.

15 minutes. I'll pull your full catalog report live.

— David Reyes`,
    status: 'REPLIED',
    sent_at: '2024-01-19T14:00:00Z',
    opened_at: '2024-01-19T16:30:00Z',
    clicked_at: '2024-01-19T16:31:00Z',
    replied_at: '2024-01-20T10:00:00Z',
    template_used: 'uncollected-royalties',
    sendgrid_message_id: 'msg_def456',
  },
  {
    id: '3',
    created_at: '2024-01-18T10:00:00Z',
    producer_id: '4',
    subject: 'Your beat on "Free Me" — $1,900/mo uncollected',
    body: `Hey D. Hill,

Pulled your IPI — no publisher on "Free Me" with 42 Dugg. You're missing about $1,900/month in publisher's share royalties.

Admin deal. No cost. 15% only on collections.

Worth a quick call?

— David`,
    status: 'SENT',
    sent_at: '2024-01-18T15:00:00Z',
    opened_at: null,
    clicked_at: null,
    replied_at: null,
    template_used: 'uncollected-royalties',
    sendgrid_message_id: 'msg_ghi789',
  },
]

export const mockStats = {
  totalLeads: 142,
  highPriority: 38,
  emailsSent: 24,
  openRate: 67,
  replies: 3,
  estimatedAnnualRoyalties: 487000,
  producersSigned: 3,
  songsScanned: 847,
}
